#!/bin/bash

# Установите в любое значение для вывода отладочной информации
# Например RUN_DEBUG="yes"
RUN_DEBUG=""

debug () {
  if [ $# -ne 1 ]
  then
    echo "debug принимает только одну строку как аргумент"
    exit 1
  fi
  if [ -n "$RUN_DEBUG" ]
  then
    echo $1
  fi
}

help () {
  echo 'Использование: run path/to/file.js'
  echo ''
  echo 'Поддерживаемые языки:'
  echo '  - JavaScript (Node.js)'
  echo '  - TypeScript (Node.js)'
  echo '  - Golang'
  echo '  - Rust'
  echo '  - Python'
  echo '  - Ruby'
  echo '  - Java'
  echo '  - C/C++'
  echo '  - PHP'
}

error () {
  echo $1
  echo
  help
  exit 1
}

case $1 in
  "--help"|"-h")
    help
    exit 0
  ;;
esac

if [ $# -ne  1 ]
then
  error "Требуется имя файла первым аргументом"
fi

FILEPATH=$1
FILENAME=$(basename "$FILEPATH")
# Определяем расширение файла
# через удаление самой длинной части подстроки,
# удовлетворяющей регулярному выражению *.
EXTENSION="${FILENAME##*.}"
# Определяем имя файла без расширения
# через удаление с конца самой короткой части подстроки,
# удовлетворяющей регулярному выражению .*
FILENAME="${FILENAME%.*}"

case $EXTENSION in
  "js")
    IMAGE="node:lts-alpine"
    COMMAND="node /app/$FILENAME.js"
    ;;
  "ts")
    IMAGE="node:lts-alpine"
    COMMAND="cd /app && npm i typescript &> /dev/null && node_modules/.bin/tsc $FILENAME.ts && node $FILENAME.js"
    ;;
  "go")
    IMAGE="golang:alpine"
    COMMAND="cd /app && go run $FILENAME.go"
    ;;
  "rs")
    IMAGE="rust:alpine"
    COMMAND="cd /app && rustc $FILENAME.rs && ./main"
    ;;
  "py")
    IMAGE="python:alpine"
    COMMAND="python3 /app/$FILENAME.py"
    ;;
  "rb")
    IMAGE="ruby:alpine"
    COMMAND="ruby /app/$FILENAME.rb"
    ;;
  "java")
    IMAGE="amazoncorretto:17"
    COMMAND="cd /app && javac $FILENAME.java && java $FILENAME"
    ;;
  "c")
    IMAGE="gcc:latest"
    COMMAND="cd /app && gcc -o main $FILENAME.c && ./main"
    ;;
  "cpp")
    IMAGE="gcc:latest"
    COMMAND="cd /app && g++ -o main $FILENAME.cpp && ./main"
    ;;
  "php")
    IMAGE="php:cli"
    COMMAND="php /app/$FILENAME.php"
    ;;
  *)
    error "Неизвестное расширение файла $EXTENSION"
    ;;
esac

# Debug
debug "IMAGE=$IMAGE"
debug "FILEPATH=$FILEPATH"
debug "FILENAME=$FILENAME"
debug "EXTENSION=$EXTENSION"
debug "COMMAND=$COMMAND"
debug ""

docker run \
  --rm \
  -it \
  -v `pwd`/$FILEPATH:/app/$FILENAME.$EXTENSION \
  $IMAGE \
  sh -c "$COMMAND"
